development: &default
  adapter: mysql2
  encoding: utf8
  database: pmk_dev
  host: localhost
  username: root
  password:
  pool: 10
  collation: utf8_unicode_ci

test:
  <<: *default
  database: pmk_test

production:
  <<: *default
  database: pmk_prod

